spring:
  application:
    name: Commandes
  datasource:
    url: jdbc:mysql://localhost:3306/commandesdb?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: commandes
server:
  port: 8081